version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - oracle
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - ORACLE_DSN=${ORACLE_USER}/${ORACLE_PASSWORD}@oracle:1521/ORCLPDB1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
    env_file:
      - .env
    environment:
      - ORACLE_PWD=${ORACLE_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
